{% set name = "bump2version" %}
{% set version = "0.5.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 524bde030318fe2543038defe0f77739605636fef96924883813cb290cf79c1e

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - bumpversion = bumpversion.cli:main
    - bump2version = bumpversion.cli:main

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - bumpversion
  commands:
    - bumpversion -h
    - bump2version -h

about:
  home: https://github.com/c4urself/bump2version
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: 'Version-bump your software with a single command!'

  description: |
    A small command line tool to simplify releasing software by updating all
    version strings in your source code by the correct increment. Also creates
    commits and tags:

    * version formats are highly configurable
    * works without any VCS, but happily reads tag information from and writes
      commits and tags to Git and Mercurial if available
    * just handles text files, so it's not specific to any programming language
    * supports Python2, Python3 and Pypy
  doc_url: https://github.com/c4urself/bump2version
  dev_url: https://github.com/c4urself/bump2version

extra:
  recipe-maintainers:
    - kynan
