travis:
  secure:
    BINSTAR_TOKEN: oEcBfC5OMMhklZSEiRt7Vw3/Wm7KCC70yj0bE6wOkPDCwDD1jpfOUY4kbN/9vVDUkQqTAPU1o5FzxJyk14RYQNQzhwjCuJ5ze4W16GosM1e/afseRb5yfjxJZh4KLA2CHff7jh9NnLy+lsBoq4c0niWJDRzue/N7BQp+sbEI/xN8WRdJ+6Gm+ZPO0jS6BOSxqQEO1M7fEILCuaQnsEt1cYc9qriNw2Cfj5liLpSOYzkYHv5DL6HWy0Y9fI0FmyA9Vdfu3GTYkeixVscsN4lL6Ce+4eUD+gUl9Vk6GQU4KjCxOM7YkRU0QrKBFxkuRCGXo8D8vnB5QIifLE6bufNE1uoFDg+HqXnlnBg0UNg4IxxTxh9TisKaUSIWEFFw6m6tC+5ivA1UD/cTjTCnvodYDUKK4nvEaD8jZIgXHdeyLtT5DT/O9HJDdcFM5YnmzLkY+P9o9mIE8B0EKgbVjL4HXpLwoQTLHhsamSAnoJghMXDnwqYl9oUS+PXULOqShC5zJViYLxg4JpuOU3Xse3kUKnN0S/sRJbFy1MeE7zNxqOyAi7H+tY5lLL2WDiCzc/hWU7KE2xgSJtK9i+tV1EO6YmOH6vlIqcNwl6ZxGlhrBpR8XCklXcqTEpMSJgtujW8Ln7Mu9WjvCENobBYd2bzNn3lI3VO+GCfkqUzh2ZoScbI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
